---
  - summary: |
  Проверка регистрации пользователя 
  requirement: |
    При успешной регистрации, на почту должно прийти письмо об успешной регистрации
  prerequisites: |
    открыта страница регистрации
  test-data: |
    Ссылка интернет-магазина: https://hexlet-products-store.vercel.app/
    Тестовые данные
    Логин = ilona Пароль = password Почта: Pesnr887@gmail.com
  steps:
    - Вводим логин
    - Вводим пароль
    - Вводим почту
    - Нажимаем кнопку "Зарегистрироваться"
  expected-result: |
    Пользователь должен попасть на главную страницу

    - summary: |
    Проверка входа пользователя с существующими логином и паролем
  requirement: |
    При верном вводе логине и пароля пользователь должен войти в систему
  prerequisites: |
    открыта страница логина
  test-data: |
    Ссылка интернет-магазина: https://hexlet-products-store.vercel.app/
    Тестовые данные
    Логин = ilona Пароль = password
  steps:
    - Вводим логин
    - Вводим пароль
    - Нажимаем кнопку "Войти"
  expected-result: |
    Пользователь должен попасть на главную страницу
    
- summary: |
    Проверка функции смены языка с английского на русский
requirement: |
    При выборе русского языка, содержимое страницы должно стать на русском языке
prerequisites:
    Открыта страница интернет-магазина (по умолчанию язык английский)
test-data: |
     Ссылка интернет-магазина: https://hexlet-products-store.vercel.app/
steps:
    - Нажимаем на список "Lanuage"
    - Выбираем русский язык
expected-result: |
    Содержимое интернет-магазина должно стать на русском языке

- summary: |
    Проверка функции добавления товара в корзину
requirement: |
    При нажатие кнопки "В корзину", выбранный товар должен добавиться в корзину
prerequisites:
    Открыта страница интернет-магазина
test-data: |
     Ссылка интернет-магазина: https://hexlet-products-store.vercel.app/
steps:
    - Выбираем любой товар
    - Нажимаем на кнопку "В корзину"
    - Переходим в корзину
expected-result: |
    Пользователь должен увидеть в корзине добавленный товар

- summary: |
    Проверка функции удаления товара из корзины
requirement: |
    При удалении товара из корзины, он должен из неё пропасть
prerequisites:
    Открыта страница интернет-магазина
test-data: |
     Ссылка интернет-магазина: https://hexlet-products-store.vercel.app/
steps:
    - Выбираем любой товар
    - Нажимаем на кнопку "В корзину"
    - Переходим в корзину
    - Удаляем выбранный товар
expected-result: |
    Пользователь должен увидеть, что добавленный товар удален из корзины

- summary: |
    Проверка функции оформления заказа 
requirement: |
    При нажатие кнопки "оформить заказ", на почту должно прийти письмо об успешном заказе и краткой информации о заказе
prerequisites:
    Открыта страница корзина интернет-магазина
test-data: |
     Ссылка интернет-магазина: https://hexlet-products-store.vercel.app/
steps:
    - Выбираем любой товар
    - Нажимаем на кнопку "В корзину"
    - Переходим в корзину
    - Нажимаем на кнопку "Оформить заказ"
expected-result: |
    Должно всплыть окно о успешном оформлении заказа, и на почту должно прийти письмо об успешном заказе и краткой информации о заказе
    
- summary: |
    Проверка поиска товара по ключевому слову
requirement: |
    При вводе в форму поиска "Iphone 9" должен отобразиться нужный товар 
prerequisites: |
    открыта страница интернет-магазина
test-data: |
    Ссылка интернет-магазина: https://hexlet-products-store.vercel.app/
    Ключевое слово "Iphone 9"
steps:
    - нажимаем на форму "Поиск"
    - Вводим "Iphone 9"
expected-result: |
    Пользователь должен увидеть карточку с товаром "Iphone 9"

- summary: |
    Проверка поиска товара по категории
requirement: |
    При выборе в форме категрии "laptops" сайт должен выдать пользователю перечень товаров из этой категории
prerequisites: |
    открыта страница интернет-магазина
test-data: |
  Ссылка интернет-магазина: https://hexlet-products-store.vercel.app/
  Ключевая категория "laptops"
steps:
    - нажимаем на форму категория
    - В выпадающем списке выбираем "laptops"
expected-result: |
    Пользователь должен увидеть карточки товаров из категории "laptops"

- summary: |
    Проверка поиска товара по категории
requirement: |
    При выборе в форме категрии "laptops" сайт должен выдать пользователю перечень товаров из этой категории
prerequisites: |
    открыта страница интернет-магазина
test-data: |
    Ссылка интернет-магазина: https://hexlet-products-store.vercel.app/
    Ключевая категория "laptops"
steps:
    - нажимаем на форму категория
    - В выпадающем списке выбираем "laptops"
expected-result: |
    Пользователь должен увидеть карточки товаров из категории "laptops"

- summary: |
    Проверка возможности просматривать подробную информацию о товаре
requirement: |
    При выборе нажатие на любой товар, сайт должен перейти на персональную страницу товара с подробной информацией о нем
prerequisites: |
    открыта страница интернет-магазина
steps:
    - Нажимаем на любой товар
expected-result: |
    Пользователь должен увидеть персональную страничку товара с подробной информацией о нем

- summary: |
    Проверка кроссплатформенности интернет-магазина
requirement: |
    Интернет-магазин должен корректно отображаться и выполнять свой функционал в полном объеме на 3-х основных браузерах (Chrome, FireFox, Safari)
prerequisites: |
    Открыты следующие браузеры: Chrome, FireFox, Safari
test-data: |
     Ссылка интернет-магазина: https://hexlet-products-store.vercel.app/
steps:
    - Заходим на сайт через браузер Chrome
    - Заходим на сайт через браузер FireFox
    - Заходим на сайт через браузер Safari
expected-result: |
    Информация на интернет-магазине для каждого браузера должна отображаться корректно. Основыные формы сайта должны быть кликабельными  

- summary: |
    Проверка адаптивности интернет-магазина для следующих устройств (смартфон, планшет, нетбук, ПК)
requirement: |
    Интрефейс интернет-магазина должен корректно отображаться и быть удобным для пользования
prerequisites: |
    Открыт сайт интернет-магазина в режиме DevTools
test-data: |
     Ссылка интернет-магазина: https://hexlet-products-store.vercel.app/
steps:
    - Заходим на сайт через браузер Chrome
    - Заходим на сайт через браузер FireFox
    - Заходим на сайт через браузер Safari
expected-result: |
    Информация на интернет-магазине для каждого браузера должна отображаться корректно. Основыные формы сайта должны быть кликабельными  
    
